[package]
name = "rush-passwd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = '0.5.1'
zip = '0.6.1'
anyhow = "1.0.65"